version: '3'

services:
  mysql-container:
    image: mysql:8.0.16
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=pass-management
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_USER=pass
  pass-management-service:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    image: leisure-pass/pass-management
    depends_on:
      - mysql-container
    ports:
      - 9090:9090
    environment:
      - mysql_url=mysql-container:3306
      - mysql_user=pass
      - mysql_password=passw0rd
      - mysql_schema_name=pass-management